### PR TITLE
Prevent permanent diff on `argocd_cluster` with sensitive attributes

### LINKED ISSUE #297: When defining args for cluster it always wants to recreate
### Terraform Version, ArgoCD Provider Version and ArgoCD Version

```
Terraform version: 1.4.6
ArgoCD provider version: 5.3
ArgoCD version: 2.7.1
```

### Affected Resource(s)

- argocd_cluster

### Terraform Configuration Files
```hcl
...
command: "kubelogin",
args: [
            "get-token",
            "--login",
            "workloadidentity",
            "--server-id",
            "6dae42f8-4368-4678-94ff-3960e28e3630",
          ]
```

### Steps to Reproduce

Every time running `terraform apply` it will suggest a change to args. Can verify that the secret in kubernetes has the correct value, it just seems like provider does not register that it is the same

### Expected Behavior

No change on apply

### Actual Behavior

```
      ~ config {
          ~ exec_provider_config {
              ~ args        = [
                  + "get-token",
                  + "--login",
                  + "workloadidentity",
                  + "--server-id",
                  + "6dae42f8-4368-4678-94ff-3960e28e3630",
                ]
                # (3 unchanged attributes hidden)
            }
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by onematchfox**
This change ensures that the `argocd_cluster` resource won't perma-diff on sensitive attributes whilst, at the same time, ensuring that we track the remote state for non-sensitive attributes that are returned by the API (see comment inline). 

Closes #297

### CODE REVIEW

File: argocd/structure_cluster.go [hunk 1]
```diff
@@ -177,15 +177,8 @@ func flattenClusterInfo(info application.ClusterInfo) []map[string]interface{} {
 func flattenClusterConfig(config application.ClusterConfig, d *schema.ResourceData) []map[string]interface{} {
 	r := map[string]interface{}{
 		"username":             config.Username,
-		"exec_provider_config": flattenClusterConfigExecProviderConfig(config.ExecProviderConfig),
-	}
-
-	if stateClusterConfig, ok := d.GetOk("config"); ok {
-		scc := expandClusterConfig(stateClusterConfig.([]interface{})[0])
```
Comment (onematchfox) [inline argocd/structure_cluster.go:184]: Rather than expanding the existing state as was done previously, this change makes use of the `TLSClientConfig` that is returned by the API, which ensures that we track the remote state of the attributes the API does return (I.e. `CAData`, `CertData`, `Insecure` and `ServerName`).

**Review by oboukili — APPROVED** [review]
